# Generated by Django 4.1.5 on 2023-01-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(default='', max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('display_picture', models.ImageField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=50, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('roll', models.CharField(default='student', max_length=15)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
