# Generated by Django 4.1.5 on 2023-01-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=50, unique=True)),
                ('time', models.TimeField(null=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
            options={
                'db_table': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Question_Bank',
            fields=[
                ('question_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.tests')),
            ],
            options={
                'db_table': 'Question_Bank',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question_bank')),
            ],
            options={
                'db_table': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_description', models.CharField(max_length=500)),
                ('display_picture', models.ImageField(null=True, upload_to='')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Course_Modules',
            fields=[
                ('module_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('module_num', models.PositiveSmallIntegerField(null=True)),
                ('module_name', models.CharField(max_length=50)),
                ('module_type', models.CharField(default=' Content ', max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('progress', models.PositiveSmallIntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.tests')),
            ],
            options={
                'db_table': 'Course_Modules',
            },
        ),
    ]
