# Generated by Django 4.1.5 on 2023-01-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_modules',
            name='module_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course_modules',
            name='module_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
