# Generated by Django 4.1.5 on 2023-01-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_modules_module_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_modules',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='course_modules',
            name='test_id',
        ),
    ]
