# Generated by Django 4.1.5 on 2023-01-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_modules_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_modules',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.tests'),
        ),
        migrations.AddField(
            model_name='tests',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
    ]
