# Generated by Django 4.1.5 on 2023-01-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_modules_test_id_tests_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_modules',
            old_name='Description',
            new_name='module_description',
        ),
        migrations.AlterField(
            model_name='course_modules',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
