# Generated by Django 4.1.5 on 2023-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_description_course_modules_module_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_modules',
            name='module_num',
            field=models.IntegerField(null=True),
        ),
    ]
