# Generated by Django 4.1.5 on 2023-01-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_modules_module_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_name',
            field=models.CharField(max_length=50),
        ),
    ]
